Make dot script update dotfiles first

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -44,6 +44,8 @@ while test $# -gt 0; do
 	shift
 done
 
+(cd $dotfiles_dir && git pull -q --ff-only && echo "Updated" || echo "Couldn't update dotfiles")
+
 $dotfiles_dir/script/bootstrap
 
 if [ "$should_install" = "true" ]
